[package]
name = "audioserve"
version = "0.20.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>", "Ilya <ilya.tepikin@gmail.com>"]
edition = "2018"

[workspace]
members = ["crates/*"]

[dependencies]

bytes = "1.0"
rand = "0.8.5"
env_logger = "0.9"
log = {version="0.4", features = ["release_max_level_info", "max_level_trace"]}
hyper = {version="0.14", features = ["full"]}
tokio-tungstenite = "0.17.2"
headers = "0.3"
futures = "0.3"
futures-channel = "0.3"
mime = "0.3"
serde_json = "1.0"
serde = {version="1.0", features=["derive"]}
serde_yaml = "0.8"
clap = "2"
lazy_static = "1.4"
thiserror = "1.0"
anyhow = "1.0"
url = "2.2"
percent-encoding = "2.1"
num_cpus = "1.13"
ring = "0.16"
data-encoding = "2.3"
regex = "1.4"
tokio = {version="1.2", features=["full"]}
uuid = {version = "1.1.2", features = ["v4"]}

# tracing-mutex = "0.2"
dashmap = "5.3.4"

dirs = "4.0"
csv = "1.1"
linked-hash-map = {git="https://github.com/izderadicka/linked-hash-map.git", version="0.5.3", features=["serde_impl"]}

# for tls
rustls ={version="0.20", optional=true}
tokio-rustls = { version="0.23", optional=true, default-features = false}
futures-util = { version = "0.3", default-features = false, optional=true }
rustls-pemfile = { version = "1", optional=true}

leaky-cauldron = {path="crates/leaky-cauldron"}
tokio-util = {version="0.6", optional=true, features=["codec"]}
cron = {version="0.9", optional=true}
chrono = {version="0.4", optional=true}


# this repo dependencies
collection = {path="crates/collection", features=["async"]}
proxy-headers = {path="crates/proxy-headers", optional=true}
simple-file-cache = {path="crates/file-cache", features=["asynch"], optional=true }
async-tar = {path="crates/async-tar", optional=true}
async-zip = {path="crates/async-zip", optional=true}
websock = {path="crates/websock", optional = true}

[target.'cfg(unix)'.dependencies]
nix = "0.23"

[features]
default = ["tls", "symlinks", "folder-download", "shared-positions", "behind-proxy"]
# default
tls=["rustls", "tokio-rustls", "futures-util", "rustls-pemfile"]
symlinks=["collection/symlinks"]

folder-download = ["async-tar", "async-zip"]
folder-download-default-tar =[]
shared-positions = ["websock", "cron", "chrono"]
behind-proxy = ["proxy-headers"]
# non-default
transcoding-cache=["simple-file-cache", "tokio-util"]
# for static compilation only
partially-static = ["collection/partially-static"]
static = ["collection/static"]
collation = ["collection/collation"]
collation-static = ["collection/collation-static"]
tags-encoding = ["collection/tags-encoding"]



[profile.release]
lto = true
codegen-units = 1

[dev-dependencies]
reqwest = {version="0.11", features=['blocking', 'json'], default-features = false}
escargot = "0.5" 
tempdir = "0.3"
