[package]
name = "media-info"
version = "0.2.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2021"

[dependencies]
thiserror = "1.0"
encoding = {version="0.2", optional=true}
lofty = { path = "../../../lofty-rs" }
